spring.datasource.url=jdbc:mysql://pharmacy-db-cloud-nguyenhoang2942004-2a7c.e.aivencloud.com:10983/defaultdb?sslMode=REQUIRED&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET:pharmacySecretKey2024VeryLongAndSecure12345}
app.jwt.expiration=86400000
